--- #YAML:1.0
name:               ZCS-Admin
version:            0.06
abstract:           module for the Zimbra Collaboration Suite (ZCS) Admin web services
author:
    - Phil Pearl <phil@zimbra.com>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Class::Std:  0.011
    SOAP::WSDL:  2.00.10
    Test::More:  0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.55_02
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
